### ISSUE TITLE
Redirected to login page

### ISSUE THREAD

**Issue by Cheaterflums** [raptor-group/keycloak-login-recaptcha#1]
Hey guys,
thank you very much for making this awesome plugin public, I really appreciate it.

The following is happening to me using Keycloak 4.5.0:
When I want to login to my application, it shows the recaptcha, but when I then login, it just redirects me back to the login page but this time without recaptcha. If I then log in again, it works. Is it somehow possible that you just have to login once instead of two times?

**Comment by unikzforce** [comment]
Hey there, Hi:), sorry for my late response.
did you set the configs written in this link:
[Official Keycloak Recaptcha configs](https://www.keycloak.org/docs/latest/server_admin/index.html#_recaptcha)

**Comment by unikzforce** [comment]
i mean `X-Frame-Options` and etc.

**Comment by Cheaterflums** [comment]
thanks for replying at all! :) I got it sorted, was just missing the correct config in browser flow!

But I still got one question: If I try to login and enter a wrong password, but with recaptcha checked, it tells me on the next page that the username/password is incorrect and there the recaptcha is missing, so if I then try to login with the correct login, it isn't accepted as the recaptcha is missing (see pictures)
![unbenannt](https://user-images.githubusercontent.com/33873948/47950996-085b0180-df5b-11e8-8876-74c529bbcf43.PNG)

![unbenannt2](https://user-images.githubusercontent.com/33873948/47951000-1e68c200-df5b-11e8-9382-146a3307cbc6.PNG)



thanks in advance!

**Comment by ksadjad** [comment]
We are informed with this issue and we're trying to fix this.

**Comment by unikzforce** [comment]
thanks to @jabolina this issues has been resolved
