### ISSUE TITLE
Add the steps "for enabling it IN GUI" - doesn't activate otherwise!

### ISSUE THREAD

**Issue by anodynos** [raptor-group/keycloak-login-recaptcha#13]
Add the steps after "for enabling it IN GUI do these: Go To authentication" from https://stackoverflow.com/questions/46974448/how-to-implement-recaptcha-on-keycloak-login-page/52517325#52517325

**Comment by unikzforce** [comment]
Hey there, please check the README again. If the problem was mitigated feel free to close the issue.

**Comment by anodynos** [comment]
Hey thanks @unikzforce - I actually prefer the doc explanation on [StackOverflow](https://stackoverflow.com/questions/46974448/how-to-implement-recaptcha-on-keycloak-login-page/52517325#52517325) - maybe you can just reference it along with yours. Thanks

**Comment by unikzforce** [comment]
@anodynos Yeah sure, That one is mine too, I'll add pictures to this one too.

**Comment by anodynos** [comment]
Thank you so much, and for this library also!

**Comment by unikzforce** [comment]
You're welcome Angelos, I'm glad that I could help a bit.
