### ISSUE TITLE
 recaptchar disappeared after an unsuccessful login

### ISSUE THREAD

**Issue by YipingRuan** [raptor-group/keycloak-login-recaptcha#2]
keycloak server 4.6
Followed the guide at [stackoverflow](https://stackoverflow.com/questions/46974448/how-to-implement-recaptcha-on-keycloak-login-page/). I managed to build and added to keycloak server. But the recaptchar disappeared after an unsuccessful login. 

![capture](https://user-images.githubusercontent.com/5492274/49055375-4da8e100-f232-11e8-89ad-637f947251aa.PNG)

![capture](https://user-images.githubusercontent.com/5492274/49055331-2ce08b80-f232-11e8-989e-94e49370b079.PNG)

By the way, what is the designed result if the user click login without complete the recaptcha challenge?

**Comment by YipingRuan** [comment]
I added to the wrong place, please close this,...

**Comment by unikzforce** [comment]
#1 
don't have time right now :(. your contributions and Pull Requests are appreciated.

**Comment by jabolina** [comment]
Was able to correct this when overriding the `createLoginForm`, something like this:
```
@Override
    protected Response createLoginForm( LoginFormsProvider form ) {
        logger.info( "Recreating login form" );
        form.setAttribute( "recaptchaRequired", true );
        form.setAttribute( "recaptchaSiteKey", siteKey );
        return super.createLoginForm( form );
    }
```

**Comment by unikzforce** [comment]
@jabolina would you please make a PR. Anyway i can add it my self too.
Appreciate your effort

**Comment by unikzforce** [comment]
thanks to @jabolina this issues has been resolved
