### ISSUE TITLE
Not working on Keycloak 7

### ISSUE THREAD

**Issue by dodyagung** [raptor-group/keycloak-login-recaptcha#3]
Tried to install this plugin on Keycloak 7, followed all instruction, but the "Recaptcha Username Password Form" option is not shown in "Add Execution", and captcha was not appeared.

Based on https://stackoverflow.com/a/52517325 guide.

**Comment by unikzforce** [comment]
thanks to @jabolina this issues has been resolved

**Comment by dodyagung** [comment]
thanks @unikzforce . I have tried it but the "Config" option was not appeared as shown at https://stackoverflow.com/a/52517325.

**Comment by unikzforce** [comment]
I'll check it soon

**Comment by unikzforce** [comment]
With the new version, It's working sir. Feel free to reopen it if you had any problem.
