### ISSUE TITLE
Recaptcha Username Password Form not available

### ISSUE THREAD

**Issue by MozkitoKiller** [raptor-group/keycloak-login-recaptcha#33]
Following the steps to add Recpatcha to my login page, after add the .jar file into the deployments the step Recaptcha Username Password Form  don't show up for me on my flow configuration. I'm mounting it on /opt/jboss/keycloak/standalone/deployments and my keycloak version is bitnami/keycloak:20.0.3-debian-11-r10

**Comment by unikzforce** [comment]
Hey sorry due to lack of time i'm not able to maintain this extension any more, but Pull Requests are much appreciated

**Comment by MozkitoKiller** [comment]
i understand. i'm trying to implement and once i get it right i will open o PR. tks!
